version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: reminders-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: reminders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: reminders-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/reminders_db?sslmode=disable
      - JWT_SECRET=tu_secreto_super_seguro_bento
    depends_on:
      - db

volumes:
  postgres_data: