# my-reminders-backend/docker-compose.yml
version: '3.8'

services:
  # Definimos el servicio de la Base de Datos
  db:
    # Usamos la imagen oficial de Postgres, versión 15 sobre Alpine Linux (ultra ligera)
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always # Se reinicia si Docker se apaga

    # CONFIGURACIÓN ESENCIAL (Variables de Entorno)
    environment:
      - POSTGRES_USER=myuser         # Usuario administrador local
      - POSTGRES_PASSWORD=mypassword # Contraseña (¡cámbiala si quieres!)
      - POSTGRES_DB=reminders_db    # Nombre de la base de datos para la App

    # MAPEADO DE PUERTOS
    ports:
      - "5432:5432" # Mapea puerto local (izq) al puerto del contenedor (der)

    # PERSISTENCIA DE DATOS (Vital)
    volumes:
      - pgdata:/var/lib/postgresql/data # Guarda los datos en un volumen nombrado

# Definimos el volumen nombrado para que los datos no se borren al apagar el contenedor
volumes:
  pgdata: