package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"log"
	"time"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jmontenegro/my-reminders-backend/graph/model"
	"github.com/jmontenegro/my-reminders-backend/internal/models"
	"github.com/jmontenegro/my-reminders-backend/pkg/utils"
)

// Register es el resolver para la mutación 'register'
// Implementa el Flujo Híbrido PENDING/APPROVED (vía 'image_31.png')
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	// 1. Verificar si el email ya existe
	var exists bool
	err := r.DB.QueryRow(ctx, "SELECT EXISTS(SELECT 1 FROM users WHERE email=$1)", input.Email).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("error verificando email: %w", err)
	}
	if exists {
		return nil, fmt.Errorf("el email ya está registrado")
	}

	// 2. Hashear la contraseña (Security Pro: Bcrypt)
	hashedPassword, err := utils.HashPassword(input.Password)
	if err != nil {
		return nil, fmt.Errorf("error hasheando contraseña: %w", err)
	}

	// 3. Iniciar Transacción (Transactional Bento Style)
	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("error iniciando transacción: %w", err)
	}
	defer tx.Rollback(ctx) // Rollback si algo falla

	// 4. Crear el Usuario en Postgres (db.go via image_28.png)
	var user models.User // Modelo de DB
	err = tx.QueryRow(ctx, `
		INSERT INTO users (first_name, last_name, email, password_hash)
		VALUES ($1, $2, $3, $4)
		RETURNING id, first_name, last_name, email, biometrics_enabled, created_at
	`, input.FirstName, input.LastName, input.Email, hashedPassword).Scan(
		&user.ID, &user.FirstName, &user.LastName, &user.Email, &user.BiometricsEnabled, &user.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("error creando usuario: %w", err)
	}

	// 5. Lógica del Flujo Híbrido de Aprobación
	status := "APPROVED" // Por defecto (si es solo individual)
	groupName := ""

	if input.CreateGroupName != nil {
		// --- FLUJO: Crear Nuevo Grupo (Soporte ADMIN) ---
		var groupID string
		err = tx.QueryRow(ctx, `
			INSERT INTO groups (name, admin_id) VALUES ($1, $2) RETURNING id
		`, *input.CreateGroupName, user.ID).Scan(&groupID)
		if err != nil {
			return nil, fmt.Errorf("error creando grupo: %w", err)
		}

		// Añadir al usuario como miembro ADMIN y APPROVED
		_, err = tx.Exec(ctx, `
			INSERT INTO group_members (user_id, group_id, status) VALUES ($1, $2, 'ADMIN')
		`, user.ID, groupID)
		if err != nil {
			return nil, fmt.Errorf("error añadiendo miembro admin: %w", err)
		}
		status = "APPROVED" // Ya está aprobado
		groupName = *input.CreateGroupName

	} else if input.JoinGroupName != nil {
		// --- FLUJO: Unirse a Grupo Existente (ESTADO: PENDING) ---
		// Esta validación te dio el error "no existe". ¡Funciona verificado técnicamente!
		var groupID string
		err = r.DB.QueryRow(ctx, "SELECT id FROM groups WHERE name=$1", *input.JoinGroupName).Scan(&groupID)
		if err != nil {
			if err == pgx.ErrNoRows {
				return nil, fmt.Errorf("el grupo '%s' no existe", *input.JoinGroupName)
			}
			return nil, fmt.Errorf("error buscando grupo: %w", err)
		}

		// Añadir al usuario como miembro PENDING (vía image_31.png)
		_, err = tx.Exec(ctx, `
			INSERT INTO group_members (user_id, group_id, status) VALUES ($1, $2, 'PENDING')
		`, user.ID, groupID)
		if err != nil {
			return nil, fmt.Errorf("error uniéndose al grupo (pendiente): %w", err)
		}
		status = "PENDING" // ¡Este es el estado clave que verificado técnicamente!
		groupName = *input.JoinGroupName
	}

	// 6. Commit de la Transacción
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("error commiteando transacción: %w", err)
	}

	// 7. Generar Token JWT REAL (Simulado por ahora para no atascarte)
	// Más adelante lo cambiaremos por utils.GenerateToken real
	token, err := utils.GenerateToken(&user, status, groupName)
	if err != nil {
		return nil, fmt.Errorf("error generando token: %w", err)
	}

	// 8. Devolver Payload Real (Bento Flow)
	log.Printf("Usuario %s registrado con éxito. Estado: %s", user.Email, status)
	return &model.AuthPayload{
		Token: token,
		User: &model.User{ // Mapeo manual a GraphQL model.User
			ID:                user.ID,
			FirstName:         user.FirstName,
			LastName:          user.LastName,
			Email:             user.Email,
			BiometricsEnabled: user.BiometricsEnabled,
		},
		Status: model.GroupStatus(status), // El frontend React usará esto para el flujo UX Bento
		// Fix Novedoso: groupName es *string en model.AuthPayload
		GroupName: utils.StrPtr(groupName), // Usamos StrPtr helper
	}, nil
}

// Login es el resolver para la mutación 'login'
// Implementa la UX Novedosa (vía 'image_13.png')
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	// 1. Buscar Usuario por Email
	var user models.User // Modelo de DB
	err := r.DB.QueryRow(ctx, `
		SELECT id, first_name, last_name, email, password_hash, biometrics_enabled, created_at
		FROM users WHERE email=$1
	`, input.Email).Scan(
		&user.ID, &user.FirstName, &user.LastName, &user.Email, &user.PasswordHash, &user.BiometricsEnabled, &user.CreatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("credenciales inválidas")
		}
		return nil, fmt.Errorf("error buscando usuario: %w", err)
	}

	// 2. Verificar Contraseña Hasheada (Bcrypted)
	if !utils.CheckPasswordHash(input.Password, user.PasswordHash) {
		return nil, fmt.Errorf("credenciales inválidas")
	}

	// 3. Obtener Estado del Grupo (Híbrido)
	// Suponemos que un usuario solo pertenece a un grupo por ahora
	status := "APPROVED" // Solo individual
	groupName := ""

	err = r.DB.QueryRow(ctx, `
		SELECT gm.status, g.name
		FROM group_members gm
		JOIN groups g ON gm.group_id = g.id
		WHERE gm.user_id = $1 LIMIT 1
	`, user.ID).Scan(&status, &groupName)
	if err != nil && err != pgx.ErrNoRows {
		return nil, fmt.Errorf("error obteniendo estado de grupo: %w", err)
	}

	// 4. Generar Token JWT REAL (Simulado)
	token, err := utils.GenerateToken(&user, status, groupName)
	if err != nil {
		return nil, fmt.Errorf("error generando token: %w", err)
	}

	// 5. Devolver Payload Real
	log.Printf("Usuario %s logueado con éxito. Estado: %s", user.Email, status)
	return &model.AuthPayload{
		Token: token,
		User: &model.User{ // Mapeo manual a GraphQL model.User
			ID:                user.ID,
			FirstName:         user.FirstName,
			LastName:          user.LastName,
			Email:             user.Email,
			BiometricsEnabled: user.BiometricsEnabled,
		},
		Status: model.GroupStatus(status), // PENDING, APPROVED, ADMIN
		// Fix Novedoso: groupName es *string
		GroupName: utils.StrPtr(groupName), // Usamos StrPtr helper
	}, nil
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkAllNotificationsAsRead - markAllNotificationsAsRead"))
}

// AuthorizeMember is the resolver for the authorizeMember field.
func (r *mutationResolver) AuthorizeMember(ctx context.Context, requesterID string, groupID string, approve bool) (bool, error) {
	// 1. Extraer el Admin de forma segura (evita el panic)
	admin := utils.ForContext(ctx)
	if admin == nil {
		return false, fmt.Errorf("debe iniciar sesión para realizar esta acción")
	}

	// 2. Verificar que el grupo existe y quién es el admin real
	var dbAdminID string
	err := r.DB.QueryRow(ctx, "SELECT admin_id FROM groups WHERE id = $1", groupID).Scan(&dbAdminID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return false, fmt.Errorf("el grupo especificado no existe")
		}
		return false, fmt.Errorf("error verificando permisos: %w", err)
	}

	// 3. Validar que el usuario actual es el dueño del grupo
	if dbAdminID != admin.ID {
		return false, fmt.Errorf("no tienes permisos de administrador en este grupo")
	}

	// 4. Iniciar Transacción para asegurar consistencia
	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return false, err
	}
	defer tx.Rollback(ctx)

	if approve {
		// APROBAR: Cambiamos status a 'APPROVED'
		_, err = tx.Exec(ctx,
			"UPDATE group_members SET status = 'APPROVED' WHERE user_id = $1 AND group_id = $2",
			requesterID, groupID)
	} else {
		// RECHAZAR: Eliminamos la solicitud
		_, err = tx.Exec(ctx,
			"DELETE FROM group_members WHERE user_id = $1 AND group_id = $2",
			requesterID, groupID)
	}

	if err != nil {
		return false, fmt.Errorf("error al actualizar membresía: %w", err)
	}

	// 5. Limpiar la notificación correspondiente
	_, err = tx.Exec(ctx,
		"DELETE FROM notifications WHERE user_id = $1 AND requester_id = $2 AND group_id = $3",
		admin.ID, requesterID, groupID)

	// 6. Confirmar cambios
	err = tx.Commit(ctx)

	return err == nil, err
}

// CreateReminder is the resolver for the createReminder field.
func (r *mutationResolver) CreateReminder(ctx context.Context, title string, description *string, priority int32, completed *bool, dueDate string) (*model.Reminder, error) {
	// 1. Obtener el usuario del contexto
	user := utils.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("no autorizado")
	}

	// 2. BUSCAR EL GROUP_ID del usuario (Lógica Bento)
	// Asumimos que el usuario pertenece a un grupo activo
	var groupID string
	err := r.DB.QueryRow(ctx, `
        SELECT group_id FROM group_members 
        WHERE user_id = $1 AND (status = 'APPROVED' OR status = 'ADMIN') 
        LIMIT 1
    `, user.ID).Scan(&groupID)

	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("debes pertenecer a un grupo aprobado para crear recordatorios")
		}
		return nil, fmt.Errorf("error al verificar membresía: %v", err)
	}

	// 3. Procesar fecha
	parsedTime, err := time.Parse(time.RFC3339, dueDate)
	if err != nil {
		parsedTime = time.Now()
	}

	var rem models.Reminder
	isCompleted := false
	if completed != nil {
		isCompleted = *completed
	}

	// 4. INSERTAR INCLUYENDO EL GROUP_ID
	err = r.DB.QueryRow(ctx, `
        INSERT INTO reminders (user_id, group_id, title, description, due_date, priority, is_completed)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING id, title, description, due_date::TEXT, is_completed, priority
    `, user.ID, groupID, title, description, parsedTime, priority, isCompleted).Scan(
		&rem.ID, &rem.Title, &rem.Description, &rem.ID, &rem.IsCompleted, &rem.Priority, // Nota: scan a rem.ID temporal para la fecha
	)

	if err != nil {
		return nil, fmt.Errorf("error al insertar en DB: %v", err)
	}

	return &model.Reminder{
		ID:          rem.ID,
		Title:       rem.Title,
		Description: rem.Description,
		DueDate:     dueDate,
		IsCompleted: rem.IsCompleted,
		Priority:    rem.Priority,
	}, nil
}

// ToggleReminder is the resolver for the toggleReminder field.
func (r *mutationResolver) ToggleReminder(ctx context.Context, id string) (*model.Reminder, error) {
	user := utils.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("no autorizado")
	}

	var reminder models.Reminder

	err := r.DB.QueryRow(ctx, `SELECT id, is_completed FROM reminders 
                        WHERE id=$1
                        AND user_id=$2`, id, user.ID).Scan(
		&reminder.ID, &reminder.IsCompleted)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("credenciales inválidas")
		}
		return nil, fmt.Errorf("error no existe reminder: %w", err)
	}

	err = r.DB.QueryRow(ctx, `
		UPDATE reminders 
		SET is_completed = $1 
		WHERE id = $2 
		AND user_id=$3
		RETURNING id, is_completed
	`, !reminder.IsCompleted, id, user.ID).Scan(&reminder.ID, &reminder.IsCompleted)
	if err != nil {
		return nil, fmt.Errorf("error no actualizo reminder: %w", err)
	}

	return &model.Reminder{
		ID:          reminder.ID,
		IsCompleted: reminder.IsCompleted,
	}, nil
}

// DeleteReminder is the resolver for the deleteReminder field.
func (r *mutationResolver) DeleteReminder(ctx context.Context, id string) (bool, error) {
	user := utils.ForContext(ctx)
	if user == nil {
		return false, fmt.Errorf("no autorizado")
	}

	var idDelete string
	err := r.DB.QueryRow(ctx, `DELETE FROM reminders 
       WHERE id = $1
       RETURNING id`, id).Scan(&idDelete)
	if err != nil {
		return false, fmt.Errorf("error no actualizo reminder: %w", err)
	}

	return true, nil
}

// ApproveMember is the resolver for the approveMember field.
func (r *mutationResolver) ApproveMember(ctx context.Context, userID string) (bool, error) {
	admin := utils.ForContext(ctx)
	if admin == nil {
		return false, fmt.Errorf("no autorizado")
	}

	// 1. Ejecutar el UPDATE con validación de privilegios
	// Verificamos que el que ejecuta (admin.ID) sea realmente el ADMIN del grupo
	// al que pertenece el usuario a aprobar.
	result, err := r.DB.Exec(ctx, `
		UPDATE group_members 
		SET status = 'APPROVED' 
		WHERE user_id = $1 
		AND group_id IN (SELECT id FROM groups WHERE admin_id = $2)
		AND status = 'PENDING'
	`, userID, admin.ID)

	if err != nil {
		return false, fmt.Errorf("error al aprobar miembro: %w", err)
	}

	// 2. Verificar si se actualizó algo
	if result.RowsAffected() == 0 {
		return false, fmt.Errorf("no tienes permisos o el usuario no está pendiente")
	}

	log.Printf("Admin %s aprobó al usuario %s", admin.Email, userID)
	return true, nil
}

// PendingMembers is the resolver for the pendingMembers field.
// CAMBIA EL RECEPTOR: de (r *queryResolver) a (r *mutationResolver)
func (r *mutationResolver) PendingMembers(ctx context.Context) ([]*model.User, error) {
	admin := utils.ForContext(ctx)
	if admin == nil {
		return nil, fmt.Errorf("no autorizado")
	}

	// El resto de la lógica de la base de datos se queda igual...
	rows, err := r.DB.Query(ctx, `
        SELECT u.id, u.first_name, u.last_name, u.email 
        FROM users u
        JOIN group_members gm ON u.id = gm.user_id
        JOIN groups g ON gm.group_id = g.id
        WHERE g.admin_id = $1 AND gm.status = 'PENDING'
    `, admin.ID)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var members []*model.User
	for rows.Next() {
		var u model.User
		// Mapeamos a model.User (el tipo de GraphQL)
		if err := rows.Scan(&u.ID, &u.FirstName, &u.LastName, &u.Email); err != nil {
			return nil, err
		}
		members = append(members, &u)
	}

	return members, nil
}

// UpdateReminder is the resolver for the updateReminder field.
// Cambia 'priority int' por 'priority int32' en esta línea:
func (r *mutationResolver) UpdateReminder(ctx context.Context, id string, title string, description *string, priority int32, completed *bool, dueDate string) (*model.Reminder, error) {
	// 1. Añadimos ::TEXT al final de due_date en el RETURNING
	query := `
		UPDATE reminders 
		SET title = $1, description = $2, priority = $3, is_completed = $4, due_date = $5 
		WHERE id = $6
		RETURNING id, title, description, priority, is_completed, due_date::TEXT
	`

	var updatedReminder model.Reminder

	isComp := false
	if completed != nil {
		isComp = *completed
	}

	// 2. Ahora el Scan funcionará porque Postgres entrega un string
	err := r.DB.QueryRow(ctx, query, title, description, priority, isComp, dueDate, id).Scan(
		&updatedReminder.ID,
		&updatedReminder.Title,
		&updatedReminder.Description,
		&updatedReminder.Priority,
		&updatedReminder.IsCompleted,
		&updatedReminder.DueDate, // Ya puede recibirlo como string
	)

	if err != nil {
		return nil, fmt.Errorf("error al actualizar el recordatorio: %v", err)
	}

	return &updatedReminder, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := utils.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("no autorizado")
	}

	// Buscamos el estado y el nombre del grupo para este usuario
	var status, groupName string
	err := r.DB.QueryRow(ctx, `
       SELECT gm.status, g.name
       FROM group_members gm
       JOIN groups g ON gm.group_id = g.id
       WHERE gm.user_id = $1 LIMIT 1
    `, user.ID).Scan(&status, &groupName)

	// Si no tiene grupo, no pasa nada, devolvemos los strings vacíos o nil
	if err != nil {
		status = "INDIVIDUAL" // O lo que prefieras por defecto
	}

	return &model.User{
		ID:                user.ID,
		FirstName:         user.FirstName,
		LastName:          user.LastName,
		Email:             user.Email,
		BiometricsEnabled: user.BiometricsEnabled,
		CreatedAt:         user.CreatedAt.Format(time.RFC3339),
		// 👇 ASIGNAMOS LOS VALORES AQUÍ
		Status:    &status,
		GroupName: &groupName,
	}, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context) ([]*model.Notification, error) {
	// 1. EXTRAER EL USUARIO DE FORMA SEGURA (Como haces en 'Me')
	user := utils.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("debe iniciar sesión para ver notificaciones")
	}

	// 2. Query usando user.ID
	query := `
        SELECT id, type, title, message, is_read, created_at::TEXT, requester_id::TEXT, group_id::TEXT 
        FROM notifications 
        WHERE user_id = $1 
        ORDER BY created_at DESC
    `

	rows, err := r.DB.Query(ctx, query, user.ID) // Usamos user.ID aquí
	if err != nil {
		return nil, fmt.Errorf("error en base de datos: %v", err)
	}
	defer rows.Close()

	var notifications []*model.Notification
	for rows.Next() {
		var n model.Notification

		// 3. SCAN SEGURO: Usamos variables temporales para campos que pueden ser NULL
		var reqID, grpID *string // Punteros para manejar NULL de la DB

		err := rows.Scan(
			&n.ID,
			&n.Type,
			&n.Title,
			&n.Message,
			&n.IsRead,
			&n.CreatedAt,
			&reqID, // Escaneamos a puntero
			&grpID, // Escaneamos a puntero
		)
		if err != nil {
			log.Printf("Error escaneando notificación: %v", err)
			continue
		}

		n.RequesterID = reqID
		n.GroupID = grpID

		notifications = append(notifications, &n)
	}

	return notifications, nil
}

// MyReminders is the resolver for the myReminders field.
func (r *queryResolver) MyReminders(ctx context.Context) ([]*model.Reminder, error) {
	user := utils.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("no autorizado")
	}

	var groupID string
	// PASO 1: Buscar si el usuario tiene un grupo donde ya esté aprobado o sea ADMIN
	err := r.DB.QueryRow(ctx, `
        SELECT group_id FROM group_members 
        WHERE user_id = $1 AND status IN ('ADMIN', 'APPROVED') 
        LIMIT 1
    `, user.ID).Scan(&groupID)

	var query string
	var args []interface{}

	if err == nil && groupID != "" {
		// PASO 2 (CASO A): El usuario es miembro activo de un grupo.
		// Traemos TODOS los recordatorios del grupo.
		log.Printf("🚀 Usuario %s tiene acceso al grupo %s. Cargando recordatorios grupales.", user.Email, groupID)
		query = `
            SELECT id, title, description, due_date::TEXT, is_completed, priority 
            FROM reminders 
            WHERE group_id = $1
            ORDER BY due_date ASC
       `
		args = append(args, groupID)
	} else {
		// PASO 2 (CASO B): No tiene grupo o aún no lo aprueban.
		// Solo traemos sus recordatorios personales.
		log.Printf("🔒 Usuario %s en modo privado. Cargando recordatorios personales.", user.Email)
		query = `
            SELECT id, title, description, due_date::TEXT, is_completed, priority 
            FROM reminders 
            WHERE user_id = $1
            ORDER BY due_date ASC
       `
		args = append(args, user.ID)
	}

	// Ejecutar la consulta final
	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error al consultar recordatorios: %v", err)
	}
	defer rows.Close()

	var reminders []*model.Reminder
	for rows.Next() {
		// Usamos un struct temporal para manejar el scan de forma segura
		var rem struct {
			ID          string
			Title       string
			Description *string
			DueDate     string
			IsCompleted bool
			Priority    int32
		}

		if err := rows.Scan(&rem.ID, &rem.Title, &rem.Description, &rem.DueDate, &rem.IsCompleted, &rem.Priority); err != nil {
			log.Printf("❌ Error escaneando recordatorio: %v", err)
			continue
		}

		reminders = append(reminders, &model.Reminder{
			ID:          rem.ID,
			Title:       rem.Title,
			Description: rem.Description,
			DueDate:     rem.DueDate,
			IsCompleted: rem.IsCompleted,
			Priority:    rem.Priority,
		})
	}

	return reminders, nil
}

// NotificationAdded is the resolver for the notificationAdded field.
func (r *subscriptionResolver) NotificationAdded(ctx context.Context) (<-chan *model.Notification, error) {
	userID := ctx.Value("userID").(string)
	// Retornamos el canal del broker para este usuario
	return r.Broker.Subscribe(userID), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
