// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	Token     string      `json:"token"`
	User      *User       `json:"user"`
	Status    GroupStatus `json:"status"`
	GroupName *string     `json:"groupName,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Notification struct {
	ID          string  `json:"id"`
	Type        string  `json:"type"`
	Title       string  `json:"title"`
	Message     string  `json:"message"`
	IsRead      bool    `json:"isRead"`
	CreatedAt   string  `json:"createdAt"`
	RequesterID *string `json:"requesterId,omitempty"`
	GroupID     *string `json:"groupId,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	FirstName       string  `json:"firstName"`
	LastName        string  `json:"lastName"`
	Email           string  `json:"email"`
	Password        string  `json:"password"`
	JoinGroupName   *string `json:"joinGroupName,omitempty"`
	CreateGroupName *string `json:"createGroupName,omitempty"`
}

type Reminder struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	DueDate     string  `json:"dueDate"`
	IsCompleted bool    `json:"isCompleted"`
	Priority    int32   `json:"priority"`
}

type Subscription struct {
}

type User struct {
	ID                string  `json:"id"`
	FirstName         string  `json:"firstName"`
	LastName          string  `json:"lastName"`
	Email             string  `json:"email"`
	BiometricsEnabled bool    `json:"biometricsEnabled"`
	CreatedAt         string  `json:"createdAt"`
	Status            *string `json:"status,omitempty"`
	GroupName         *string `json:"groupName,omitempty"`
}

type GroupStatus string

const (
	GroupStatusPending  GroupStatus = "PENDING"
	GroupStatusApproved GroupStatus = "APPROVED"
	GroupStatusAdmin    GroupStatus = "ADMIN"
)

var AllGroupStatus = []GroupStatus{
	GroupStatusPending,
	GroupStatusApproved,
	GroupStatusAdmin,
}

func (e GroupStatus) IsValid() bool {
	switch e {
	case GroupStatusPending, GroupStatusApproved, GroupStatusAdmin:
		return true
	}
	return false
}

func (e GroupStatus) String() string {
	return string(e)
}

func (e *GroupStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GroupStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GroupStatus", str)
	}
	return nil
}

func (e GroupStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GroupStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GroupStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
